package enums;

public enum InvalidEmailType {
    DOMAIN_TYPO,
    INVALID_TLD,
    MISSING_TLD,
    DOUBLE_DOT_DOMAIN,
    NO_AT_SYMBOL,
    DOUBLE_AT,
    DOUBLE_DOT_LOCAL,
    DOT_AT_START,
    DOT_AT_END,
    INVALID_DOMAIN_ONLY_NUMBERS,
    TOO_SHORT_DOMAIN,
    NON_ASCII_CHARACTERS,
    EMPTY_EMAIL,
    ONLY_SYMBOLS,
    UNALLOWED_SPECIAL_CHARS
}
